### ISSUE TITLE
flatiron_stats module missing from master branch

### ISSUE THREAD

**Issue by Freddy-2021** [learn-co-curriculum/dsc-website-ab-testing-lab#1]
### Canvas Link

https://github.com/learn-co-curriculum/dsc-website-ab-testing-lab/tree/solution

### Concern

Following along the qith 'solutions branch' code for this lesson I tried to import the 'flatiron_stats' module but I received an error stating the module was not found 
input : import flatiron_stats as fs

output: ModuleNotFoundError: No module named 'flatiron_stats'

**Comment by Cheffrey2000** [comment]
[3055e80](https://github.com/learn-co-curriculum/dsc-website-ab-testing-lab/commit/3055e803a26741e260dfe8115d0526c8bdcc3f9e)
Thank you for raising this issue, @Freddy-2021
