### ISSUE TITLE
Dsc website ab testing error

### ISSUE THREAD

**Issue by Dmvinedata** [learn-co-curriculum/dsc-website-ab-testing-lab#2]
## Link to Canvas

https://github.com/learn-co-curriculum/dsc-website-ab-testing-lab/tree/solution

## Issue Subtype

- [ ] Master branch code
- [ x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
print("Number of Clickers who didn't view: {}".format(len(cids-vids)))
```

### Concern

To check who didn't view, there should be code that subtracts the non-viewers from the clickers.
The solution code has clickers from viewers
"print("Number of Clickers who didn't view: {}".format(len(cids-vids)))"

## (Optional) Proposed Solution

#Numbers of clickers who didn't view
    #The difference between non views and clicks
   #Total views = 8188, numV 6328
NonV = 8188 - NumV
print ("The number of views who didnt click:", NumC-NonV)

## What OS Are You Using?

- [ x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by Dmvinedata** [comment]
I realized the github is correct, since it was using "set".  My issue can be removed.

**Comment by jessepisel** [comment]
Thanks for opening this issue @Dmvinedata 👋 . Looks like you have addressed the issue you opened above. I will go ahead and close it at this time.
