### ISSUE TITLE
Import flatiron_stats as fs 

### ISSUE THREAD

**Issue by Nurul-ain2022** [learn-co-curriculum/dsc-website-ab-testing-lab#3]
Import flatiron_stats as fs does not work on the notebook could there be a disconnect somewhere?

**Comment by Cheffrey2000** [comment]
This issue has been fixed with the following commit [3055e80](https://github.com/learn-co-curriculum/dsc-website-ab-testing-lab/commit/3055e803a26741e260dfe8115d0526c8bdcc3f9e)

**Comment by Cheffrey2000** [comment]
Thank you for raising this issue, @Nurul-ain2022
